import {
  AIAuditResult,
  AlertItem,
  AppLocaleMetadata,
  AppSummary,
  CompetitorApp,
  KeywordRow,
} from "@/types";

export const MOCK_APPS: AppSummary[] = [
  {
    id: "app_water_eject",
    appStoreId: "1459896708",
    bundleId: "com.appgrowth.watereject",
    name: "Water Eject - Speaker Cleaner",
    developerName: "App Growth Labs",
    category: "Utilities",
    iconUrl: "/mock/icons/water-eject.png",
    ratingAverage: 4.7,
    ratingCount: 18342,
    currentVersion: "3.4.1",
    price: 0,
    storeUrl: "https://apps.apple.com/us/app/water-eject/id1459896708",
    isOwned: true,
    trackedKeywords: 48,
    top10Keywords: 12,
    metadataNeedsUpdate: true,
  },
  {
    id: "app_focus_timer",
    appStoreId: "1289561039",
    bundleId: "com.appgrowth.focustimer",
    name: "Focus Timer - Pomodoro Planner",
    developerName: "App Growth Labs",
    category: "Productivity",
    iconUrl: "/mock/icons/focus-timer.png",
    ratingAverage: 4.8,
    ratingCount: 9221,
    currentVersion: "2.1.0",
    price: 0,
    storeUrl: "https://apps.apple.com/us/app/focus-timer/id1289561039",
    isOwned: true,
    trackedKeywords: 36,
    top10Keywords: 9,
    metadataNeedsUpdate: false,
  },
  {
    id: "app_habit_loop",
    appStoreId: "1402233771",
    bundleId: "com.appgrowth.habitloop",
    name: "Habit Loop - Daily Tracker",
    developerName: "App Growth Labs",
    category: "Health & Fitness",
    iconUrl: "/mock/icons/habit-loop.png",
    ratingAverage: 4.5,
    ratingCount: 4109,
    currentVersion: "1.9.4",
    price: 0,
    storeUrl: "https://apps.apple.com/us/app/habit-loop/id1402233771",
    isOwned: true,
    trackedKeywords: 22,
    top10Keywords: 3,
    metadataNeedsUpdate: true,
  },
];

export const MOCK_LOCALE_METADATA: Record<string, AppLocaleMetadata[]> = {
  app_water_eject: [
    {
      localeCode: "en-US",
      title: "Water Eject - Speaker Cleaner",
      subtitle: "Remove water from speaker fast",
      promotionalText: "New sound wave patterns added for deeper cleaning power.",
      keywordsField: "water eject,speaker cleaner,remove water,clean speaker,sound cleaner,wet phone",
      description: "Water Eject helps you clear water trapped in your phone's speaker using calibrated sound frequencies...",
      releaseNotes: "Bug fixes and performance improvements.",
      supportUrl: "https://appgrowthlabs.com/support",
      marketingUrl: "https://appgrowthlabs.com/watereject",
      privacyUrl: "https://appgrowthlabs.com/privacy",
      screenshotUrls: ["/mock/shots/we-1.png", "/mock/shots/we-2.png", "/mock/shots/we-3.png"],
    },
    {
      localeCode: "de-DE",
      title: "Wasser Eject - Lautsprecher reinigen",
      subtitle: "Wasser schnell entfernen",
      promotionalText: "Neue Klangmuster für tiefere Reinigung.",
      keywordsField: "wasser entfernen,lautsprecher reinigen,handy reinigen,klang,wasserschaden",
      description: "Wasser Eject hilft dir, eingeschlossenes Wasser aus dem Lautsprecher deines Handys zu entfernen...",
      releaseNotes: "Fehlerbehebungen und Leistungsverbesserungen.",
      supportUrl: "https://appgrowthlabs.com/support",
      marketingUrl: "https://appgrowthlabs.com/watereject",
      privacyUrl: "https://appgrowthlabs.com/privacy",
      screenshotUrls: ["/mock/shots/we-1.png", "/mock/shots/we-2.png", "/mock/shots/we-3.png"],
    },
  ],
};

function genHistory(seedRank: number) {
  return Array.from({ length: 14 }).map((_, i) => {
    const date = new Date();
    date.setDate(date.getDate() - (13 - i));
    const drift = Math.round(Math.sin(i / 2) * 3);
    const rank = Math.max(1, seedRank + drift);
    return { date: date.toISOString().slice(0, 10), rank };
  });
}

export const MOCK_KEYWORDS: KeywordRow[] = [
  {
    id: "kw_1",
    appId: "app_water_eject",
    term: "speaker cleaner",
    countryCode: "US",
    localeCode: "en-US",
    currentRank: 9,
    previousRank: 4,
    bestRank: 2,
    difficultyScore: 62,
    volumeScore: 81,
    intent: "HIGH_INTENT",
    cluster: "Tool keywords",
    status: "FALLING",
    lastCheckedAt: new Date().toISOString(),
    history: genHistory(6),
  },
  {
    id: "kw_2",
    appId: "app_water_eject",
    term: "water eject",
    countryCode: "US",
    localeCode: "en-US",
    currentRank: 1,
    previousRank: 1,
    bestRank: 1,
    difficultyScore: 40,
    volumeScore: 70,
    intent: "BRANDED",
    cluster: "Branded",
    status: "WINNING",
    lastCheckedAt: new Date().toISOString(),
    history: genHistory(1),
  },
  {
    id: "kw_3",
    appId: "app_water_eject",
    term: "remove water from phone",
    countryCode: "US",
    localeCode: "en-US",
    currentRank: 14,
    previousRank: 21,
    bestRank: 14,
    difficultyScore: 48,
    volumeScore: 55,
    intent: "PROBLEM",
    cluster: "Problem keywords",
    status: "OPPORTUNITY",
    lastCheckedAt: new Date().toISOString(),
    history: genHistory(18),
  },
  {
    id: "kw_4",
    appId: "app_water_eject",
    term: "sound cleaner app",
    countryCode: "US",
    localeCode: "en-US",
    currentRank: null,
    previousRank: null,
    bestRank: null,
    difficultyScore: 35,
    volumeScore: 28,
    intent: "BROAD",
    cluster: "Tool keywords",
    status: "NOT_RANKING",
    lastCheckedAt: new Date().toISOString(),
    history: genHistory(45),
  },
  {
    id: "kw_5",
    appId: "app_water_eject",
    term: "wasser aus lautsprecher",
    countryCode: "DE",
    localeCode: "de-DE",
    currentRank: 6,
    previousRank: 11,
    bestRank: 6,
    difficultyScore: 30,
    volumeScore: 42,
    intent: "PROBLEM",
    cluster: "Local language keywords",
    status: "OPPORTUNITY",
    lastCheckedAt: new Date().toISOString(),
    history: genHistory(9),
  },
  {
    id: "kw_6",
    appId: "app_water_eject",
    term: "shower shortcuts cleaner",
    countryCode: "US",
    localeCode: "en-US",
    currentRank: 31,
    previousRank: 19,
    bestRank: 19,
    difficultyScore: 56,
    volumeScore: 19,
    intent: "COMPETITOR",
    cluster: "Competitor keywords",
    status: "FALLING",
    lastCheckedAt: new Date().toISOString(),
    history: genHistory(25),
  },
];

export const MOCK_COMPETITORS: Record<string, CompetitorApp[]> = {
  app_water_eject: [
    {
      id: "comp_1",
      appStoreId: "1130667716",
      name: "Sonic - Speaker Water Eject",
      subtitle: "Clean speakers with sound waves",
      iconUrl: "/mock/icons/comp-1.png",
      category: "Utilities",
      ratingAverage: 4.6,
      ratingCount: 52310,
      sharedKeywords: 21,
      betterRankCount: 8,
      missedKeywords: 13,
    },
    {
      id: "comp_2",
      appStoreId: "1248912933",
      name: "Clear Wave: Speaker Cleaner",
      subtitle: "Remove water instantly",
      iconUrl: "/mock/icons/comp-2.png",
      category: "Utilities",
      ratingAverage: 4.4,
      ratingCount: 11820,
      sharedKeywords: 17,
      betterRankCount: 4,
      missedKeywords: 6,
    },
    {
      id: "comp_3",
      appStoreId: "1391029122",
      name: "Speaker Boost & Cleaner",
      subtitle: "Boost volume and clean speaker",
      iconUrl: "/mock/icons/comp-3.png",
      category: "Utilities",
      ratingAverage: 4.2,
      ratingCount: 3490,
      sharedKeywords: 9,
      betterRankCount: 2,
      missedKeywords: 3,
    },
  ],
};

export const MOCK_AI_AUDIT: Record<string, AIAuditResult> = {
  app_water_eject: {
    asoScore: 68,
    metadataScore: 61,
    keywordOpportunityScore: 74,
    conversionRiskScore: 55,
    screenshotScore: 70,
    localizationScore: 48,
    competitorPressureScore: 66,
    diagnosis:
      "Your title and keyword field both repeat 'water' and 'speaker', wasting characters that could target new high-intent terms. 'speaker cleaner' dropped from #4 to #9 in the US in the last 10 days while a competitor refreshed their subtitle to include the same term.",
    keywordOpportunity: [
      "remove water from phone",
      "iphone speaker water",
      "phone water damage fix",
      "speaker sound restore",
    ],
    metadataRewrite: {
      title: "Water Eject: Speaker Cleaner",
      subtitle: "Fix Muffled Sound Fast",
    },
    keywordField:
      "remove water,wet phone,sound restore,muffled fix,speaker boost,clean app,audio repair,water damage",
    countryNotes:
      "US: prioritize problem-based phrasing ('remove water from phone') over branded terms. Germany: 'wasser aus lautsprecher' is rising and under-targeted relative to volume.",
    competitorInsight:
      "Top competitor 'Sonic' ranks #2-#4 across your shared keyword set by leading with the symptom ('muffled sound') in the subtitle instead of the mechanism ('sound waves'). Their keyword field avoids repeating their title words entirely.",
    appleAdsExactMatchList: [
      "remove water from phone",
      "speaker water damage",
      "muffled speaker fix",
      "wet phone speaker",
    ],
    whatNotToDo: [
      "Don't repeat 'water' and 'eject' across title, subtitle and keyword field — it's wasted character budget.",
      "Don't bid broad match on 'cleaner app' — CPT is high and conversion intent is low.",
      "Don't translate German metadata literally; localize around the symptom phrase, not the literal mechanism.",
    ],
    sevenDayPlan: [
      "Day 1-2: Update subtitle to lead with the symptom, not the mechanism.",
      "Day 3: Rewrite keyword field to remove duplicate words with title/subtitle.",
      "Day 4-5: Launch Apple Ads exact match test on 4 problem-based keywords.",
      "Day 6-7: Monitor rank movement on 'speaker cleaner' and 'remove water from phone'.",
    ],
    thirtyDayPlan: [
      "Week 1: Metadata refresh + exact match ASA test.",
      "Week 2: Add German localized keyword set targeting 'wasser aus lautsprecher' cluster.",
      "Week 3: Update screenshot 1 headline to match new subtitle messaging.",
      "Week 4: Re-audit ASO score and compare competitor pressure score movement.",
    ],
  },
};

export const MOCK_ALERTS: AlertItem[] = [
  {
    id: "alert_1",
    type: "RANK_DROP",
    message: "Water Eject dropped from #4 to #9 for 'speaker cleaner' in US",
    appId: "app_water_eject",
    createdAt: new Date().toISOString(),
  },
  {
    id: "alert_2",
    type: "COMPETITOR_CHANGE",
    message: "Competitor 'Sonic' changed subtitle to include 'muffled sound'",
    appId: "app_water_eject",
    createdAt: new Date().toISOString(),
  },
  {
    id: "alert_3",
    type: "KEYWORD_OPPORTUNITY",
    message: "Keyword opportunity found in Brazil: 'tirar água do celular'",
    appId: "app_water_eject",
    createdAt: new Date().toISOString(),
  },
  {
    id: "alert_4",
    type: "METADATA_WARNING",
    message: "Title/subtitle duplicate keyword warning on Habit Loop",
    appId: "app_habit_loop",
    createdAt: new Date().toISOString(),
  },
];
